version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # uninstall Node.js v10 from CodeBuild's image
      - yes | n uninstall

      # install Node.js v13
      - curl -sL https://deb.nodesource.com/setup_13.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - npm ci --verbose
  build:
    commands:
      # run the build
      - npm run build
artifacts:
  secondary-artifacts:
    service:
      files:
        - '**/*'
    static:
      files:
        - '**/*'
      base-directory: 'build'